apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: chatbot-b1731322477000
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jrichter/chbot1:0290e61f6842942aeaa86eaeebf23e0ed0706ba3@sha256:d8010fd1200b9e69afd558fb3e037efb7100cca08d6878cad2f3e3ee361ddd19 # use pre-built to bootstrap 
          name: app-inference
