apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: chatbot-b1731322477000
  janus-idp.io/tekton: chatbot-b1731322477000
  backstage.io/kubernetes-id: chatbot-b1731322477000
  backstage.io/kubernetes-namespace: ai-rhdh-app-development 
  app.kubernetes.io/part-of: chatbot-b1731322477000
resources: 
- initialize-namespace.yaml
- deployment.yaml
- route.yaml
- service.yaml
- model-config.yaml
